export const hasta = {
    tcno : 12345678910,
    isim : "Olivia Wilson",
    babaAdi : "Ahmet",
    dogumTarihi : "13/05/1980",
    email : "olivia@wilson.com",
    tel : "+47 123 456 2222",
    adres : "Toronto Kanada", 
    disİslem : {
        1 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi devam ediyor'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}],
        2 : [{kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        3 : [{kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'eksik/çekilmiş'},
            {kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'}
            
        ],
        4 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        5 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        6 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        7 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        8 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        9 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        10 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        11 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        12 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        13 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        14 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        15 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        16 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        17 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        18 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        19 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        20 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        21 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        22 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        23 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        24 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        25 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        26 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        27 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        28 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        29 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        30 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        31 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
        32 : [{kategori:'Pedodonti',
            tedavi:'Kanal Tedavisi',
            islemTarih:'10.01.2023',
            islemNotu:'Geçici dolgu yapıldı.',
            durum:'Tedavi Devam Ediyor.'},
            {kategori:'Cerrahi',
            tedavi:'Dolgu',
            islemTarih:'19.12.2022',
            islemNotu:'İlerde nüks edebilir.',
            durum:'Tedavi Tamamlandı.'},
            {kategori:'Estetidonti',
            tedavi:'Beyazlatma',
            islemTarih:'12.12.2022',
            islemNotu:'Mine katmanı inceldi.',
            durum:'Tedavi Tamamlandı.'}
        ],
    }
}