export const dental = [
	{
		id: 1,
		name: "Egemen",
		lastName: "Yılmaz",
		phone: "0555 212 58 96",
		email: "egemenyilmaz@inci.com",
		gender: "Bay",
		img: "https://placeimg.com/50/50/people",
		expertise: "Ortodonti",
	},
	{
		id: 2,
		name: "Çağrı",
		lastName: "Yılmaz",
		phone: "0532 541 75 86",
		email: "cagrıyilmaz@inci.com",
		gender: "Bay",
		img: "https://placeimg.com/60/60/people",
		expertise: "Diş Hekimi",
	},
	{
		id: 3,
		name: "Levent",
		lastName: "Kaya",
		phone: "0545 754 12 96",
		email: "leventkaya@inci.com",
		gender: "Bay",
		img: "https://placeimg.com/70/70/people",
		expertise: "Ağız Diş Çene Cerrahisi",
	},
	{
		id: 4,
		name: "Ayşe",
		lastName: "Suna",
		phone: "0553 286 12 43",
		email: "aysesuna@inci.com",
		gender: "Bayan",
		img: "https://placeimg.com/50/50/people",
		expertise: "Çocuk Diş Hekimi",
	},
	{
		id: 5,
		name: "Fatma",
		lastName: "Turgut",
		phone: "0554 518 17 73",
		email: "fatmaturgut@inci.com",
		gender: "Bayan",
		img: "https://placeimg.com/60/60/people",
		expertise: "Periodontoloji",
	},
	{
		id: 6,
		name: "Tülin",
		lastName: "Tan",
		phone: "0532 512 18 17",
		email: "tulintan@inci.com",
		gender: "Bayan",
		img: "https://placeimg.com/70/70/people",
		expertise: "Ortodonti",
	},
	{
		id: 7,
		name: "Faruk",
		lastName: "Doğru",
		phone: "0532 512 21 32",
		email: "farukdogru@inci.com",
		gender: "Bay",
		img: "https://placeimg.com/80/80/people",
		expertise: "Diş Hekimi",
	},
];

export const patients = [
	{
		id: 1,
		name: "Barış",
		lastName: "Korkmaz",
		gender: "Bay",
		clock: "11:00",
		descriptions: "Kanal tedavisine devam edilecek",
	},
	{
		id: 2,
		name: "Yusuf",
		lastName: "Kal",
		gender: "Bay",
		clock: "10:30",
		descriptions: "Diş Eti Absesi ve Periodontal Abseler",
	},
	{
		id: 3,
		name: "Ayşe",
		lastName: "Sağ",
		gender: "Bayan",
		clock: "09:30",
		descriptions: "Sağ arka 5 diş çekilecek",
	},
	{
		id: 4,
		name: "Fatma",
		lastName: "Yakut",
		gender: "Bayan",
		clock: "14:30",
		descriptions: "Diş taşı temizliği yapılacak",
	},
	{
		id: 5,
		name: "Ali",
		lastName: "Sağır",
		gender: "Bay",
		clock: "11:30",
		descriptions: "",
	},
	{
		id: 6,
		name: "Yusuf",
		lastName: "Solmaz",
		gender: "Bay",
		clock: "11:00",
		descriptions: "Damak yarılması",
	},
	{
		id: 7,
		name: "Tuğba",
		lastName: "Kılıç",
		gender: "Bayan",
		clock: "12:30",
		descriptions: "Diş teli yapımı",
	},
];
