export const dental = [
	{
		id: 1,
		name: "Egemen",
		lastName: "Yılmaz",
		phone: "0555 212 58 96",
		email: "egemenyilmaz@inci.com",
		gender: "Bay",
		img: "https://placeimg.com/50/50/people",
		expertise: "Ortodonti",
	},
	{
		id: 2,
		name: "Çağrı",
		lastName: "Yılmaz",
		phone: "0532 541 75 86",
		email: "cagrıyilmaz@inci.com",
		gender: "Bay",
		img: "https://placeimg.com/60/60/people",
		expertise: "Diş Hekimi",
	},
	{
		id: 3,
		name: "Levent",
		lastName: "Kaya",
		phone: "0545 754 12 96",
		email: "leventkaya@inci.com",
		gender: "Bay",
		img: "https://placeimg.com/70/70/people",
		expertise: "Ağız Diş Çene Cerrahisi",
	},
	{
		id: 4,
		name: "Ayşe",
		lastName: "Suna",
		phone: "0553 286 12 43",
		email: "aysesuna@inci.com",
		gender: "Bayan",
		img: "https://placeimg.com/50/50/people",
		expertise: "Çocuk Diş Hekimi",
	},
	{
		id: 5,
		name: "Fatma",
		lastName: "Turgut",
		phone: "0554 518 17 73",
		email: "fatmaturgut@inci.com",
		gender: "Bayan",
		img: "https://placeimg.com/60/60/people",
		expertise: "Periodontoloji",
	},
	{
		id: 6,
		name: "Tülin",
		lastName: "Tan",
		phone: "0532 512 18 17",
		email: "tulintan@inci.com",
		gender: "Bayan",
		img: "https://placeimg.com/70/70/people",
		expertise: "Ortodonti",
	},
	{
		id: 7,
		name: "Faruk",
		lastName: "Doğru",
		phone: "0532 512 21 32",
		email: "farukdogru@inci.com",
		gender: "Bay",
		img: "https://placeimg.com/80/80/people",
		expertise: "Diş Hekimi",
	},
];

export const patients = [
	{
		id: 1,
		name: "Barış",
		lastName: "Korkmaz",
		gender: "Bay",
		clock: "11:00",
		descriptions: "Kanal tedavisine devam edilecek",
	},
	{
		id: 2,
		name: "Yusuf",
		lastName: "Kal",
		gender: "Bay",
		clock: "10:30",
		descriptions: "Diş Eti Absesi ve Periodontal Abseler",
	},
	{
		id: 3,
		name: "Ayşe",
		lastName: "Sağ",
		gender: "Bayan",
		clock: "09:30",
		descriptions: "Sağ arka 5 diş çekilecek",
	},
	{
		id: 4,
		name: "Fatma",
		lastName: "Yakut",
		gender: "Bayan",
		clock: "14:30",
		descriptions: "Diş taşı temizliği yapılacak",
	},
	{
		id: 5,
		name: "Ali",
		lastName: "Sağır",
		gender: "Bay",
		clock: "11:30",
		descriptions: "",
	},
	{
		id: 6,
		name: "Yusuf",
		lastName: "Solmaz",
		gender: "Bay",
		clock: "11:00",
		descriptions: "Damak yarılması",
	},
	{
		id: 7,
		name: "Tuğba",
		lastName: "Kılıç",
		gender: "Bayan",
		clock: "12:30",
		descriptions: "Diş teli yapımı",
	},
];

export const doktorlar = [
	{
		id: 0,
		name: "Egemen Yılmaz",
		img: "https://placeimg.com/850/850/people",
		email: "egemenyilmaz@email.com",
		phone: "0542 123 45 67",
		gender: "Erkek",
		ünvan: "Başhekim",
		adres: "Cumhuriyet Mah. 18. Cad. No:6 Merkez/Sivas",
		işbaşı: "01 Ocak 2022",
		doğum: "14 Mart 1980",
		üniversite: "Hacettepe Üniversitesi",
		istatistic: {
			bakılanhasta: {
				bugün: 12,
				birhaftadır: 34,
				biray: 52,
				biryıl: 81,
				tüm: 129,
			},
			yapılanişlem: {
				bugün: 8,
				birhaftadır: 21,
				biray: 30,
				biryıl: 40,
				tüm: 48,
			},
			kullanılanizin: {
				bugün: 0,
				birhaftadır: 1,
				biray: 5,
				biryıl: 15,
				tüm: 40,
			},
			toplammesai: {
				bugün: 8,
				birhaftadır: 30,
				biray: 200,
				biryıl: 500,
				tüm: 597,
			},
		},
		uyguladıtedavi: {
			cerrahi: {
				dişçekimi: 250,
				implant: 140,
				discekimi: 250,
				gömülüdiş: 80,
				çenekırığı: 20,
				damak: 40,
			},
			tedavi: {
				diagnoz: 14,
				konservatif: 145,
				endodonti: 421,
				pedodonti: 180,
			},
			ortodonti: {
				telgerme: 139,
				telleme: 215,
				sıkma: 751,
				gevşetme: 102,
				uydurma: 234,
				uyarlama: 145,
				sallama: 210,
				kasnakatma: 145,
				entegre: 103,
				ondoitasyon: 137,
				pufrize: 191,
			},
			radyoloji: {
				çene: 421,
				diş: 574,
				ağız: 651,
			},
			fenoloji: {
				diagnoz: 144,
				konservatif: 142,
				endodonti: 457,
				pedodonti: 42,
			},
			ağızbakım: {
				beyazlatma: 442,
				diştaşı: 412,
				endodonti: 41,
				pedodonti: 143,
			},
			cleoronti: {
				telgerme: 413,
				telleme: 132,
				sıkma: 123,
				gevşetme: 248,
				uydurma: 42,
				uyarlama: 123,
			},
			ceromonti: {
				diagnoz: 45,
				konservatif: 65,
				endodonti: 878,
				pedodonti: 465,
			},
		},
	},
	{
		id: 1,
		name: "Çelebi Doğan",
		img: "https://placeimg.com/900/900/people",
		email: "celebidogan@email.com",
		phone: "0542 142 42 67",
		gender: "Erkek",
		ünvan: "Ortodonti Uzmanı",
		adres: "Atatürk Mah. 321. Cad. No:13 Merkez/Ankara",
		işbaşı: "21 Mart 2022",
		doğum: "21 Mart 1985",
		üniversite: "Ankara Üniversitesi",
		istatistic: {
			bakılanhasta: {
				bugün: 14,
				birhaftadır: 44,
				biray: 74,
				biryıl: 85,
				tüm: 182,
			},
			yapılanişlem: {
				bugün: 4,
				birhaftadır: 41,
				biray: 52,
				biryıl: 62,
				tüm: 78,
			},
			kullanılanizin: {
				bugün: 0,
				birhaftadır: 2,
				biray: 4,
				biryıl: 25,
				tüm: 45,
			},
			toplammesai: {
				bugün: 4,
				birhaftadır: 41,
				biray: 185,
				biryıl: 502,
				tüm: 750,
			},
		},
		uyguladıtedavi: {
			cerrahi: {
				dişçekimi: 120,
				implant: 110,
				discekimi: 100,
				gömülüdiş: 40,
				çenekırığı: 14,
				damak: 15,
			},
			tedavi: {
				diagnoz: 45,
				konservatif: 421,
				endodonti: 45,
				pedodonti: 1,
			},
			ortodonti: {
				telgerme: 150,
				telleme: 123,
				sıkma: 124,
				gevşetme: 10,
				uydurma: 124,
				uyarlama: 154,
				sallama: 52,
				kasnakatma: 41,
				entegre: 274,
				ondoitasyon: 54,
				pufrize: 542,
			},
			radyoloji: {
				çene: 42,
				diş: 21,
				ağız: 452,
			},
			fenoloji: {
				diagnoz: 24,
				konservatif: 124,
				endodonti: 47,
				pedodonti: 75,
			},
			ağızbakım: {
				beyazlatma: 24,
				diştaşı: 42,
				endodonti: 42,
				pedodonti: 422,
			},
			cleoronti: {
				telgerme: 25,
				telleme: 52,
				sıkma: 41,
				gevşetme: 14,
				uydurma: 412,
				uyarlama: 41,
			},
			ceromonti: {
				diagnoz: 42,
				konservatif: 12,
				endodonti: 21,
				pedodonti: 258,
			},
		},
	},
	{
		id: 2,
		name: "Zeynep Kara",
		img: "https://placeimg.com/700/700/people",
		email: "zeynepkara@email.com",
		phone: "0541 454 23 89",
		gender: "Kadın",
		ünvan: "Diş Hekimi",
		adres: "Yavuz Selim Mah. 123. Cad. No:6 Merkez/İstanbul",
		işbaşı: "28 Şubat 2020",
		doğum: "13 Temmuz 1990",
		üniversite: "Hacettepe Üniversitesi",
		istatistic: {
			bakılanhasta: {
				bugün: 12,
				birhaftadır: 34,
				biray: 52,
				biryıl: 81,
				tüm: 129,
			},
			yapılanişlem: {
				bugün: 8,
				birhaftadır: 21,
				biray: 30,
				biryıl: 40,
				tüm: 48,
			},
			kullanılanizin: {
				bugün: 0,
				birhaftadır: 1,
				biray: 5,
				biryıl: 15,
				tüm: 40,
			},
			toplammesai: {
				bugün: 8,
				birhaftadır: 30,
				biray: 200,
				biryıl: 500,
				tüm: 597,
			},
		},
		uyguladıtedavi: {
			cerrahi: {
				dişçekimi: 250,
				implant: 140,
				discekimi: 250,
				gömülüdiş: 80,
				çenekırığı: 20,
				damak: 40,
			},
			tedavi: {
				diagnoz: 14,
				konservatif: 145,
				endodonti: 421,
				pedodonti: 180,
			},
			ortodonti: {
				telgerme: 139,
				telleme: 215,
				sıkma: 751,
				gevşetme: 102,
				uydurma: 234,
				uyarlama: 145,
				sallama: 210,
				kasnakatma: 145,
				entegre: 103,
				ondoitasyon: 137,
				pufrize: 191,
			},
			radyoloji: {
				çene: 421,
				diş: 574,
				ağız: 651,
			},
			fenoloji: {
				diagnoz: 144,
				konservatif: 142,
				endodonti: 457,
				pedodonti: 42,
			},
			ağızbakım: {
				beyazlatma: 442,
				diştaşı: 412,
				endodonti: 41,
				pedodonti: 143,
			},
			cleoronti: {
				telgerme: 413,
				telleme: 132,
				sıkma: 123,
				gevşetme: 248,
				uydurma: 42,
				uyarlama: 123,
			},
			ceromonti: {
				diagnoz: 45,
				konservatif: 65,
				endodonti: 878,
				pedodonti: 465,
			},
		},
	},
	{
		id: 3,
		name: "Mikail Çelikbaş",
		img: "https://placeimg.com/950/950/people",
		email: "mikailcelikbas@email.com",
		phone: "0532 422 45 58",
		gender: "Erkek",
		ünvan: "Diş Hekimi",
		adres: "Barbaros Mah. 23. Cad. No:12 Merkez/Bolu",
		işbaşı: "14 Nisan 2022",
		doğum: "22 Ağustos 1991",
		üniversite: "Boğaziçi Üniversitesi",
		istatistic: {
			bakılanhasta: {
				bugün: 14,
				birhaftadır: 44,
				biray: 74,
				biryıl: 85,
				tüm: 182,
			},
			yapılanişlem: {
				bugün: 4,
				birhaftadır: 41,
				biray: 52,
				biryıl: 62,
				tüm: 78,
			},
			kullanılanizin: {
				bugün: 0,
				birhaftadır: 2,
				biray: 4,
				biryıl: 25,
				tüm: 45,
			},
			toplammesai: {
				bugün: 4,
				birhaftadır: 41,
				biray: 185,
				biryıl: 502,
				tüm: 750,
			},
		},
		uyguladıtedavi: {
			cerrahi: {
				discekimi: 120,
				implant: 110,
				dişçekimi: 100,
				gömülüdiş: 40,
				çenekırığı: 14,
				damak: 15,
			},
			tedavi: {
				diagnoz: 45,
				konservatif: 421,
				endodonti: 45,
				pedodonti: 1,
			},
			ortodonti: {
				telgerme: 150,
				telleme: 123,
				sıkma: 124,
				gevşetme: 10,
				uydurma: 124,
				uyarlama: 154,
				sallama: 52,
				kasnakatma: 41,
				entegre: 274,
				ondoitasyon: 54,
				pufrize: 542,
			},
			radyoloji: {
				çene: 42,
				diş: 21,
				ağız: 452,
			},
			fenoloji: {
				diagnoz: 24,
				konservatif: 124,
				endodonti: 47,
				pedodonti: 75,
			},
			ağızbakım: {
				beyazlatma: 24,
				diştaşı: 42,
				endodonti: 42,
				pedodonti: 422,
			},
			cleoronti: {
				telgerme: 25,
				telleme: 52,
				sıkma: 41,
				gevşetme: 14,
				uydurma: 412,
				uyarlama: 41,
			},
			ceromonti: {
				diagnoz: 42,
				konservatif: 12,
				endodonti: 21,
				pedodonti: 258,
			},
		},
	},
	{
		id: 4,
		name: "Seray Kiraz",
		img: "https://placeimg.com/1100/1100/people",
		email: "seraykiraz@email.com",
		phone: "0542 123 45 67",
		gender: "Kadın",
		ünvan: "Diş Hekimi",
		adres: "Yavuz Selim Mah. 123. Cad. No:6 Merkez/İstanbul",
		işbaşı: "22 Temmuz 2020",
		doğum: "12 Mayıs 1992",
		üniversite: "Ankara Üniversitesi",
		istatistic: {
			bakılanhasta: {
				bugün: 12,
				birhaftadır: 34,
				biray: 52,
				biryıl: 81,
				tüm: 129,
			},
			yapılanişlem: {
				bugün: 8,
				birhaftadır: 21,
				biray: 30,
				biryıl: 40,
				tüm: 48,
			},
			kullanılanizin: {
				bugün: 0,
				birhaftadır: 1,
				biray: 5,
				biryıl: 15,
				tüm: 40,
			},
			toplammesai: {
				bugün: 8,
				birhaftadır: 30,
				biray: 200,
				biryıl: 500,
				tüm: 597,
			},
		},
		uyguladıtedavi: {
			cerrahi: {
				dişçekimi: 250,
				implant: 140,
				discekimi: 250,
				gömülüdiş: 80,
				çenekırığı: 20,
				damak: 40,
			},
			tedavi: {
				diagnoz: 14,
				konservatif: 145,
				endodonti: 421,
				pedodonti: 180,
			},
			ortodonti: {
				telgerme: 139,
				telleme: 215,
				sıkma: 751,
				gevşetme: 102,
				uydurma: 234,
				uyarlama: 145,
				sallama: 210,
				kasnakatma: 145,
				entegre: 103,
				ondoitasyon: 137,
				pufrize: 191,
			},
			radyoloji: {
				çene: 421,
				diş: 574,
				ağız: 651,
			},
			fenoloji: {
				diagnoz: 144,
				konservatif: 142,
				endodonti: 457,
				pedodonti: 42,
			},
			ağızbakım: {
				beyazlatma: 442,
				diştaşı: 412,
				endodonti: 41,
				pedodonti: 143,
			},
			cleoronti: {
				telgerme: 413,
				telleme: 132,
				sıkma: 123,
				gevşetme: 248,
				uydurma: 42,
				uyarlama: 123,
			},
			ceromonti: {
				diagnoz: 45,
				konservatif: 65,
				endodonti: 878,
				pedodonti: 465,
			},
		},
	},
];
