export const doktorlar = [
	{
		id: 0,
		name: "Egemen Yılmaz",
		img: "https://placeimg.com/850/850/people",
		email: "egemenyilmaz@email.com",
		phone: "0542 123 45 67",
		gender: "Erkek",
		ünvan: "Başhekim",
		adres: "Cumhuriyet Mah. 18. Cad. No:6 Merkez/Sivas",
		işbaşı: "01 Ocak 2022",
		doğum: "14 Mart 1980",
		üniversite: "Hacettepe Üniversitesi",
		istatistik: [
			{
				id: 1,
				istatistikAdi: "Bakılan Hasta",
				istatistikVeri: [
					{ zamanAdı: "Bugün", sayı: 14 },
					{ zamanAdı: "Bu Hafta", sayı: 44 },
					{ zamanAdı: "Bu Ay", sayı: 74 },
					{ zamanAdı: "Bu Yıl", sayı: 85 },
					{ zamanAdı: "Tüm Zamanlar", sayı: 182 },
				],
			},
			{
				id: 2,
				istatistikAdi: "Yapılan İşlem",
				istatistikVeri: [
					{ zamanAdı: "Bugün", sayı: 8 },
					{ zamanAdı: "Bu Hafta", sayı: 21 },
					{ zamanAdı: "Bu Ay", sayı: 45 },
					{ zamanAdı: "Bu Yıl", sayı: 85 },
					{ zamanAdı: "Tüm Zamanlar", sayı: 120 },
				],
			},
			{
				id: 3,
				istatistikAdi: "Kullanılan İzin",
				istatistikVeri: [
					{ zamanAdı: "Bugün", sayı: 4 },
					{ zamanAdı: "Bu Hafta", sayı: 4 },
					{ zamanAdı: "Bu Ay", sayı: 14 },
					{ zamanAdı: "Bu Yıl", sayı: 41 },
					{ zamanAdı: "Tüm Zamanlar", sayı: 85 },
				],
			},
			{
				id: 4,
				istatistikAdi: "Toplam Mesai",
				istatistikVeri: [
					{ zamanAdı: "Bugün", sayı: 8 },
					{ zamanAdı: "Bu Hafta", sayı: 10 },
					{ zamanAdı: "Bu Ay", sayı: 42 },
					{ zamanAdı: "Bu Yıl", sayı: 100 },
					{ zamanAdı: "Tüm Zamanlar", sayı: 124 },
				],
			},
		],
		uyguladıtedavi: [
			{
				id: 1,
				müdahaleKategori: "Cerrahi",
				müdahaleIstatistik: [
					{
						müdahaleAdı: "Diş Çekimi",
						müdahaleSayı: 250,
					},
					{ müdahaleAdı: "İmplant", müdahaleSayı: 140 },

					{ müdahaleAdı: "Gömülü Diş", müdahaleSayı: 80 },
					{ müdahaleAdı: "Çene kırığı", müdahaleSayı: 20 },
					{ müdahaleAdı: "Damak", müdahaleSayı: 40 },
				],
			},
			{
				id: 2,
				müdahaleKategori: "Tedavi",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Diagnoz", müdahaleSayı: 14 },
					{ müdahaleAdı: "Konservatif", müdahaleSayı: 145 },
					{ müdahaleAdı: "Endodonti", müdahaleSayı: 421 },
					{ müdahaleAdı: "Pedodonti", müdahaleSayı: 180 },
				],
			},
			{
				id: 3,
				müdahaleKategori: "Ortodonti",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Telgerme", müdahaleSayı: 139 },
					{ müdahaleAdı: "Telleme", müdahaleSayı: 215 },
					{ müdahaleAdı: "Sıkma", müdahaleSayı: 751 },
					{ müdahaleAdı: "Gevşetme", müdahaleSayı: 41 },
					{ müdahaleAdı: "Uydurma", müdahaleSayı: 257 },
					{ müdahaleAdı: "Uyarlama", müdahaleSayı: 789 },
					{ müdahaleAdı: "Sallama", müdahaleSayı: 455 },
					{ müdahaleAdı: "Kasnakatma", müdahaleSayı: 142 },
					{ müdahaleAdı: "Entegre", müdahaleSayı: 425 },
					{ müdahaleAdı: "Ondoitasyon", müdahaleSayı: 125 },
					{ müdahaleAdı: "Pufrize", müdahaleSayı: 131 },
				],
			},
			{
				id: 4,
				müdahaleKategori: "Radyoloji",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Çene", müdahaleSayı: 112 },
					{ müdahaleAdı: "Diş", müdahaleSayı: 131 },
					{ müdahaleAdı: "Ağız", müdahaleSayı: 445 },
				],
			},
			{
				id: 5,
				müdahaleKategori: "Fenoloji",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Diagnoz", müdahaleSayı: 45 },
					{ müdahaleAdı: "Konservatif", müdahaleSayı: 12 },
					{ müdahaleAdı: "Endodonti", müdahaleSayı: 452 },
					{ müdahaleAdı: "Pedodonti", müdahaleSayı: 80 },
				],
			},
			{
				id: 6,
				müdahaleKategori: "Ağız Bakım",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Beyazlatma", müdahaleSayı: 73 },
					{ müdahaleAdı: "Diş Taşı", müdahaleSayı: 786 },
					{ müdahaleAdı: "Diş Bakım", müdahaleSayı: 454 },
				],
			},
			{
				id: 7,
				müdahaleKategori: "Cleoronti",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Gevşetme", müdahaleSayı: 42 },
					{ müdahaleAdı: "Uydurma", müdahaleSayı: 86 },
					{ müdahaleAdı: "Telgerme", müdahaleSayı: 42 },
					{ müdahaleAdı: "Telleme", müdahaleSayı: 585 },
					{ müdahaleAdı: "Sıkma", müdahaleSayı: 58 },
					{ müdahaleAdı: "Uyarlama", müdahaleSayı: 98 },
				],
			},
			{
				id: 8,
				müdahaleKategori: "Ceromonti",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Diagnoz", müdahaleSayı: 42 },
					{ müdahaleAdı: "Konservatif", müdahaleSayı: 422 },
					{ müdahaleAdı: "Endodonti", müdahaleSayı: 475 },
					{ müdahaleAdı: "Pedodonti", müdahaleSayı: 74 },
				],
			},
		],
	},
	{
		id: 1,
		name: "Çelebi Doğan",
		img: "https://placeimg.com/900/900/people",
		email: "celebidogan@email.com",
		phone: "0542 142 42 67",
		gender: "Erkek",
		ünvan: "Ortodonti Uzmanı",
		adres: "Atatürk Mah. 321. Cad. No:13 Merkez/Ankara",
		işbaşı: "21 Mart 2022",
		doğum: "21 Mart 1985",
		üniversite: "Ankara Üniversitesi",
		istatistik: [
			{
				id: 1,
				istatistikAdi: "Bakılan Hasta",
				istatistikVeri: [
					{ zamanAdı: "Bugün", sayı: 21 },
					{ zamanAdı: "Bu Hafta", sayı: 42 },
					{ zamanAdı: "Bu Ay", sayı: 52 },
					{ zamanAdı: "Bu Yıl", sayı: 85 },
					{ zamanAdı: "Tüm Zamanlar", sayı: 254 },
				],
			},
			{
				id: 2,
				istatistikAdi: "Yapılan İşlem",
				istatistikVeri: [
					{ zamanAdı: "Bugün", sayı: 12 },
					{ zamanAdı: "Bu Hafta", sayı: 24 },
					{ zamanAdı: "Bu Ay", sayı: 34 },
					{ zamanAdı: "Bu Yıl", sayı: 53 },
					{ zamanAdı: "Tüm Zamanlar", sayı: 150 },
				],
			},
			{
				id: 3,
				istatistikAdi: "Kullanılan İzin",
				istatistikVeri: [
					{ zamanAdı: "Bugün", sayı: 1 },
					{ zamanAdı: "Bu Hafta", sayı: 7 },
					{ zamanAdı: "Bu Ay", sayı: 24 },
					{ zamanAdı: "Bu Yıl", sayı: 87 },
					{ zamanAdı: "Tüm Zamanlar", sayı: 120 },
				],
			},
			{
				id: 4,
				istatistikAdi: "Toplam Mesai",
				istatistikVeri: [
					{ zamanAdı: "Bugün", sayı: 18 },
					{ zamanAdı: "Bu Hafta", sayı: 41 },
					{ zamanAdı: "Bu Ay", sayı: 52 },
					{ zamanAdı: "Bu Yıl", sayı: 200 },
					{ zamanAdı: "Tüm Zamanlar", sayı: 321 },
				],
			},
		],
		uyguladıtedavi: [
			{
				id: 1,
				müdahaleKategori: "Cerrahi",
				müdahaleIstatistik: [
					{
						müdahaleAdı: "Diş Çekimi",
						müdahaleSayı: 241,
					},
					{ müdahaleAdı: "İmplant", müdahaleSayı: 253 },

					{ müdahaleAdı: "Gömülü Diş", müdahaleSayı: 875 },
					{ müdahaleAdı: "Çene kırığı", müdahaleSayı: 758 },
					{ müdahaleAdı: "Damak", müdahaleSayı: 7 },
				],
			},
			{
				id: 2,
				müdahaleKategori: "Tedavi",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Diagnoz", müdahaleSayı: 47 },
					{ müdahaleAdı: "Konservatif", müdahaleSayı: 58 },
					{ müdahaleAdı: "Endodonti", müdahaleSayı: 74 },
					{ müdahaleAdı: "Pedodonti", müdahaleSayı: 412 },
				],
			},
			{
				id: 3,
				müdahaleKategori: "Ortodonti",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Telgerme", müdahaleSayı: 75 },
					{ müdahaleAdı: "Telleme", müdahaleSayı: 69 },
					{ müdahaleAdı: "Sıkma", müdahaleSayı: 78 },
					{ müdahaleAdı: "Gevşetme", müdahaleSayı: 786 },
					{ müdahaleAdı: "Uydurma", müdahaleSayı: 456 },
					{ müdahaleAdı: "Uyarlama", müdahaleSayı: 435 },
					{ müdahaleAdı: "Sallama", müdahaleSayı: 95 },
					{ müdahaleAdı: "Kasnakatma", müdahaleSayı: 25 },
					{ müdahaleAdı: "Entegre", müdahaleSayı: 34 },
					{ müdahaleAdı: "Ondoitasyon", müdahaleSayı: 521 },
					{ müdahaleAdı: "Pufrize", müdahaleSayı: 434 },
				],
			},
			{
				id: 4,
				müdahaleKategori: "Radyoloji",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Çene", müdahaleSayı: 455 },
					{ müdahaleAdı: "Diş", müdahaleSayı: 351 },
					{ müdahaleAdı: "Ağız", müdahaleSayı: 354 },
				],
			},
			{
				id: 5,
				müdahaleKategori: "Fenoloji",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Diagnoz", müdahaleSayı: 12 },
					{ müdahaleAdı: "Konservatif", müdahaleSayı: 213 },
					{ müdahaleAdı: "Endodonti", müdahaleSayı: 89 },
					{ müdahaleAdı: "Pedodonti", müdahaleSayı: 785 },
				],
			},
			{
				id: 6,
				müdahaleKategori: "Ağız Bakım",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Beyazlatma", müdahaleSayı: 45 },
					{ müdahaleAdı: "Diş Taşı", müdahaleSayı: 345 },
					{ müdahaleAdı: "Diş Bakım", müdahaleSayı: 342 },
				],
			},
			{
				id: 7,
				müdahaleKategori: "Cleoronti",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Gevşetme", müdahaleSayı: 842 },
					{ müdahaleAdı: "Uydurma", müdahaleSayı: 768 },
					{ müdahaleAdı: "Telgerme", müdahaleSayı: 123 },
					{ müdahaleAdı: "Telleme", müdahaleSayı: 542 },
					{ müdahaleAdı: "Sıkma", müdahaleSayı: 5824 },
					{ müdahaleAdı: "Uyarlama", müdahaleSayı: 68 },
				],
			},
			{
				id: 8,
				müdahaleKategori: "Ceromonti",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Diagnoz", müdahaleSayı: 412 },
					{ müdahaleAdı: "Konservatif", müdahaleSayı: 120 },
					{ müdahaleAdı: "Endodonti", müdahaleSayı: 705 },
					{ müdahaleAdı: "Pedodonti", müdahaleSayı: 12 },
				],
			},
		],
	},
	{
		id: 2,
		name: "Zeynep Kara",
		img: "https://placeimg.com/700/700/people",
		email: "zeynepkara@email.com",
		phone: "0541 454 23 89",
		gender: "Kadın",
		ünvan: "Diş Hekimi",
		adres: "Yavuz Selim Mah. 123. Cad. No:6 Merkez/İstanbul",
		işbaşı: "28 Şubat 2020",
		doğum: "13 Temmuz 1990",
		üniversite: "Hacettepe Üniversitesi",
		istatistik: [
			{
				id: 1,
				istatistikAdi: "Bakılan Hasta",
				istatistikVeri: [
					{ zamanAdı: "Bugün", sayı: 32 },
					{ zamanAdı: "Bu Hafta", sayı: 35 },
					{ zamanAdı: "Bu Ay", sayı: 64 },
					{ zamanAdı: "Bu Yıl", sayı: 195 },
					{ zamanAdı: "Tüm Zamanlar", sayı: 341 },
				],
			},
			{
				id: 2,
				istatistikAdi: "Yapılan İşlem",
				istatistikVeri: [
					{ zamanAdı: "Bugün", sayı: 11 },
					{ zamanAdı: "Bu Hafta", sayı: 25 },
					{ zamanAdı: "Bu Ay", sayı: 31 },
					{ zamanAdı: "Bu Yıl", sayı: 48 },
					{ zamanAdı: "Tüm Zamanlar", sayı: 118 },
				],
			},
			{
				id: 3,
				istatistikAdi: "Kullanılan İzin",
				istatistikVeri: [
					{ zamanAdı: "Bugün", sayı: 0 },
					{ zamanAdı: "Bu Hafta", sayı: 4 },
					{ zamanAdı: "Bu Ay", sayı: 14 },
					{ zamanAdı: "Bu Yıl", sayı: 25 },
					{ zamanAdı: "Tüm Zamanlar", sayı: 87 },
				],
			},
			{
				id: 4,
				istatistikAdi: "Toplam Mesai",
				istatistikVeri: [
					{ zamanAdı: "Bugün", sayı: 8 },
					{ zamanAdı: "Bu Hafta", sayı: 40 },
					{ zamanAdı: "Bu Ay", sayı: 64 },
					{ zamanAdı: "Bu Yıl", sayı: 198 },
					{ zamanAdı: "Tüm Zamanlar", sayı: 415 },
				],
			},
		],
		uyguladıtedavi: [
			{
				id: 1,
				müdahaleKategori: "Cerrahi",
				müdahaleIstatistik: [
					{
						müdahaleAdı: "Diş Çekimi",
						müdahaleSayı: 194,
					},
					{ müdahaleAdı: "İmplant", müdahaleSayı: 241 },

					{ müdahaleAdı: "Gömülü Diş", müdahaleSayı: 741 },
					{ müdahaleAdı: "Çene kırığı", müdahaleSayı: 344 },
					{ müdahaleAdı: "Damak", müdahaleSayı: 452 },
				],
			},
			{
				id: 2,
				müdahaleKategori: "Tedavi",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Diagnoz", müdahaleSayı: 45 },
					{ müdahaleAdı: "Konservatif", müdahaleSayı: 78 },
					{ müdahaleAdı: "Endodonti", müdahaleSayı: 458 },
					{ müdahaleAdı: "Pedodonti", müdahaleSayı: 435 },
				],
			},
			{
				id: 3,
				müdahaleKategori: "Ortodonti",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Telgerme", müdahaleSayı: 74 },
					{ müdahaleAdı: "Telleme", müdahaleSayı: 95 },
					{ müdahaleAdı: "Sıkma", müdahaleSayı: 45 },
					{ müdahaleAdı: "Gevşetme", müdahaleSayı: 864 },
					{ müdahaleAdı: "Uydurma", müdahaleSayı: 532 },
					{ müdahaleAdı: "Uyarlama", müdahaleSayı: 314 },
					{ müdahaleAdı: "Sallama", müdahaleSayı: 105 },
					{ müdahaleAdı: "Kasnakatma", müdahaleSayı: 34 },
					{ müdahaleAdı: "Entegre", müdahaleSayı: 54 },
					{ müdahaleAdı: "Ondoitasyon", müdahaleSayı: 858 },
					{ müdahaleAdı: "Pufrize", müdahaleSayı: 341 },
				],
			},
			{
				id: 4,
				müdahaleKategori: "Radyoloji",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Çene", müdahaleSayı: 541 },
					{ müdahaleAdı: "Diş", müdahaleSayı: 258 },
					{ müdahaleAdı: "Ağız", müdahaleSayı: 97 },
				],
			},
			{
				id: 5,
				müdahaleKategori: "Fenoloji",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Diagnoz", müdahaleSayı: 78 },
					{ müdahaleAdı: "Konservatif", müdahaleSayı: 454 },
					{ müdahaleAdı: "Endodonti", müdahaleSayı: 358 },
					{ müdahaleAdı: "Pedodonti", müdahaleSayı: 967 },
				],
			},
			{
				id: 6,
				müdahaleKategori: "Ağız Bakım",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Beyazlatma", müdahaleSayı: 423 },
					{ müdahaleAdı: "Diş Taşı", müdahaleSayı: 123 },
					{ müdahaleAdı: "Diş Bakım", müdahaleSayı: 378 },
				],
			},
			{
				id: 7,
				müdahaleKategori: "Cleoronti",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Gevşetme", müdahaleSayı: 613 },
					{ müdahaleAdı: "Uydurma", müdahaleSayı: 712 },
					{ müdahaleAdı: "Telgerme", müdahaleSayı: 4523 },
					{ müdahaleAdı: "Telleme", müdahaleSayı: 546 },
					{ müdahaleAdı: "Sıkma", müdahaleSayı: 1323 },
					{ müdahaleAdı: "Uyarlama", müdahaleSayı: 456 },
				],
			},
			{
				id: 8,
				müdahaleKategori: "Ceromonti",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Diagnoz", müdahaleSayı: 45 },
					{ müdahaleAdı: "Konservatif", müdahaleSayı: 56 },
					{ müdahaleAdı: "Endodonti", müdahaleSayı: 12 },
					{ müdahaleAdı: "Pedodonti", müdahaleSayı: 34 },
				],
			},
		],
	},
	{
		id: 3,
		name: "Mikail Çelikbaş",
		img: "https://placeimg.com/950/950/people",
		email: "mikailcelikbas@email.com",
		phone: "0532 422 45 58",
		gender: "Erkek",
		ünvan: "Diş Hekimi",
		adres: "Barbaros Mah. 23. Cad. No:12 Merkez/Bolu",
		işbaşı: "14 Nisan 2022",
		doğum: "22 Ağustos 1991",
		üniversite: "Boğaziçi Üniversitesi",
		istatistik: [
			{
				id: 1,
				istatistikAdi: "Bakılan Hasta",
				istatistikVeri: [
					{ zamanAdı: "Bugün", sayı: 41 },
					{ zamanAdı: "Bu Hafta", sayı: 57 },
					{ zamanAdı: "Bu Ay", sayı: 86 },
					{ zamanAdı: "Bu Yıl", sayı: 257 },
					{ zamanAdı: "Tüm Zamanlar", sayı: 451 },
				],
			},
			{
				id: 2,
				istatistikAdi: "Yapılan İşlem",
				istatistikVeri: [
					{ zamanAdı: "Bugün", sayı: 19 },
					{ zamanAdı: "Bu Hafta", sayı: 32 },
					{ zamanAdı: "Bu Ay", sayı: 42 },
					{ zamanAdı: "Bu Yıl", sayı: 58 },
					{ zamanAdı: "Tüm Zamanlar", sayı: 107 },
				],
			},
			{
				id: 3,
				istatistikAdi: "Kullanılan İzin",
				istatistikVeri: [
					{ zamanAdı: "Bugün", sayı: 1 },
					{ zamanAdı: "Bu Hafta", sayı: 7 },
					{ zamanAdı: "Bu Ay", sayı: 21 },
					{ zamanAdı: "Bu Yıl", sayı: 45 },
					{ zamanAdı: "Tüm Zamanlar", sayı: 150 },
				],
			},
			{
				id: 4,
				istatistikAdi: "Toplam Mesai",
				istatistikVeri: [
					{ zamanAdı: "Bugün", sayı: 4 },
					{ zamanAdı: "Bu Hafta", sayı: 12 },
					{ zamanAdı: "Bu Ay", sayı: 123 },
					{ zamanAdı: "Bu Yıl", sayı: 452 },
					{ zamanAdı: "Tüm Zamanlar", sayı: 682 },
				],
			},
		],
		uyguladıtedavi: [
			{
				id: 1,
				müdahaleKategori: "Cerrahi",
				müdahaleIstatistik: [
					{
						müdahaleAdı: "Diş Çekimi",
						müdahaleSayı: 123,
					},
					{ müdahaleAdı: "İmplant", müdahaleSayı: 42 },

					{ müdahaleAdı: "Gömülü Diş", müdahaleSayı: 456 },
					{ müdahaleAdı: "Çene kırığı", müdahaleSayı: 736 },
					{ müdahaleAdı: "Damak", müdahaleSayı: 789 },
				],
			},
			{
				id: 2,
				müdahaleKategori: "Tedavi",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Diagnoz", müdahaleSayı: 32 },
					{ müdahaleAdı: "Konservatif", müdahaleSayı: 456 },
					{ müdahaleAdı: "Endodonti", müdahaleSayı: 876 },
					{ müdahaleAdı: "Pedodonti", müdahaleSayı: 1231 },
				],
			},
			{
				id: 3,
				müdahaleKategori: "Ortodonti",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Telgerme", müdahaleSayı: 42 },
					{ müdahaleAdı: "Telleme", müdahaleSayı: 4536 },
					{ müdahaleAdı: "Sıkma", müdahaleSayı: 789 },
					{ müdahaleAdı: "Gevşetme", müdahaleSayı: 787 },
					{ müdahaleAdı: "Uydurma", müdahaleSayı: 5723 },
					{ müdahaleAdı: "Uyarlama", müdahaleSayı: 656 },
					{ müdahaleAdı: "Sallama", müdahaleSayı: 34 },
					{ müdahaleAdı: "Kasnakatma", müdahaleSayı: 786 },
					{ müdahaleAdı: "Entegre", müdahaleSayı: 12 },
					{ müdahaleAdı: "Ondoitasyon", müdahaleSayı: 35 },
					{ müdahaleAdı: "Pufrize", müdahaleSayı: 564 },
				],
			},
			{
				id: 4,
				müdahaleKategori: "Radyoloji",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Çene", müdahaleSayı: 213 },
					{ müdahaleAdı: "Diş", müdahaleSayı: 354 },
					{ müdahaleAdı: "Ağız", müdahaleSayı: 456 },
				],
			},
			{
				id: 5,
				müdahaleKategori: "Fenoloji",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Diagnoz", müdahaleSayı: 123 },
					{ müdahaleAdı: "Konservatif", müdahaleSayı: 753 },
					{ müdahaleAdı: "Endodonti", müdahaleSayı: 456 },
					{ müdahaleAdı: "Pedodonti", müdahaleSayı: 698 },
				],
			},
			{
				id: 6,
				müdahaleKategori: "Ağız Bakım",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Beyazlatma", müdahaleSayı: 410 },
					{ müdahaleAdı: "Diş Taşı", müdahaleSayı: 453 },
					{ müdahaleAdı: "Diş Bakım", müdahaleSayı: 453 },
				],
			},
			{
				id: 7,
				müdahaleKategori: "Cleoronti",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Gevşetme", müdahaleSayı: 435 },
					{ müdahaleAdı: "Uydurma", müdahaleSayı: 456 },
					{ müdahaleAdı: "Telgerme", müdahaleSayı: 212 },
					{ müdahaleAdı: "Telleme", müdahaleSayı: 453 },
					{ müdahaleAdı: "Sıkma", müdahaleSayı: 213 },
					{ müdahaleAdı: "Uyarlama", müdahaleSayı: 54 },
				],
			},
			{
				id: 8,
				müdahaleKategori: "Ceromonti",
				müdahaleIstatistik: [
					{ müdahaleAdı: "Diagnoz", müdahaleSayı: 67 },
					{ müdahaleAdı: "Konservatif", müdahaleSayı: 89 },
					{ müdahaleAdı: "Endodonti", müdahaleSayı: 76 },
					{ müdahaleAdı: "Pedodonti", müdahaleSayı: 89 },
				],
			},
		],
	},
	{
		id: 4,
		name: "Seray Kiraz",
		img: "https://placeimg.com/1100/1100/people",
		email: "seraykiraz@email.com",
		phone: "0542 123 45 67",
		gender: "Kadın",
		ünvan: "Diş Hekimi",
		adres: "Yavuz Selim Mah. 123. Cad. No:6 Merkez/İstanbul",
		işbaşı: "22 Temmuz 2020",
		doğum: "12 Mayıs 1992",
		üniversite: "Ankara Üniversitesi",
		istatistik: [
			{
				id: 1,
				istatistikAdi: "Bakılan Hasta",
				istatistikVeri: {
					bugün: 21,
					birhaftadır: 100,
					biray: 245,
					biryıl: 385,
					tüm: 862,
				},
			},
			{
				id: 2,
				istatistikAdi: "Yapılan İşlem",
				istatistikVeri: {
					bugün: 25,
					birhaftadır: 134,
					biray: 368,
					biryıl: 862,
					tüm: 2124,
				},
			},
			{
				id: 3,
				istatistikAdi: "Kullanılan İzin",
				istatistikVeri: {
					bugün: 1,
					birhaftadır: 1,
					biray: 2,
					biryıl: 5,
					tüm: 11,
				},
			},
			{
				id: 4,
				istatistikAdi: "Toplam Mesai",
				istatistikVeri: {
					bugün: 10,
					birhaftadır: 68,
					biray: 258,
					biryıl: 1240,
					tüm: 2534,
				},
			},
		],
		uyguladıtedavi: [
			{
				id: 1,
				müdahaleKategori: "cerrahi",
				müdahaleIstatistik: [
					{
						müdahaleAdı: "dişçekimi",
						müdahaleSayı: 782,
					},
					{ müdahaleAdı: "implant", müdahaleSayı: 453 },

					{ müdahaleAdı: "gömülüdiş", müdahaleSayı: 245 },
					{ müdahaleAdı: "Çene kırığı", müdahaleSayı: 96 },
					{ müdahaleAdı: "damak", müdahaleSayı: 786 },
				],
			},
			{
				id: 2,
				müdahaleKategori: "tedavi",
				müdahaleIstatistik: [
					{ müdahaleAdı: "diagnoz", müdahaleSayı: 452 },
					{ müdahaleAdı: "konservatif", müdahaleSayı: 645 },
					{ müdahaleAdı: "endodonti", müdahaleSayı: 87 },
					{ müdahaleAdı: "pedodonti", müdahaleSayı: 68 },
				],
			},
			{
				id: 3,
				müdahaleKategori: "ortodonti",
				müdahaleIstatistik: [
					{ müdahaleAdı: "diagnoz", müdahaleSayı: 456 },
					{ müdahaleAdı: "konservatif", müdahaleSayı: 789 },
					{ müdahaleAdı: "endodonti", müdahaleSayı: 879 },
					{ müdahaleAdı: "pedodonti", müdahaleSayı: 645 },
				],
			},
			{
				id: 4,
				müdahaleKategori: "radyoloji",
				müdahaleIstatistik: [
					{ müdahaleAdı: "diagnoz", müdahaleSayı: 41 },
					{ müdahaleAdı: "konservatif", müdahaleSayı: 414 },
					{ müdahaleAdı: "endodonti", müdahaleSayı: 255 },
					{ müdahaleAdı: "pedodonti", müdahaleSayı: 453 },
				],
			},
			{
				id: 5,
				müdahaleKategori: "fenoloji",
				müdahaleIstatistik: [
					{ müdahaleAdı: "diagnoz", müdahaleSayı: 45 },
					{ müdahaleAdı: "konservatif", müdahaleSayı: 54 },
					{ müdahaleAdı: "endodonti", müdahaleSayı: 35 },
					{ müdahaleAdı: "pedodonti", müdahaleSayı: 457 },
				],
			},
			{
				id: 6,
				müdahaleKategori: "ağız bakım",
				müdahaleIstatistik: [
					{ müdahaleAdı: "diagnoz", müdahaleSayı: 879 },
					{ müdahaleAdı: "konservatif", müdahaleSayı: 456 },
					{ müdahaleAdı: "endodonti", müdahaleSayı: 56 },
					{ müdahaleAdı: "pedodonti", müdahaleSayı: 45 },
				],
			},
			{
				id: 7,
				müdahaleKategori: "cleoronti",
				müdahaleIstatistik: [
					{ müdahaleAdı: "diagnoz", müdahaleSayı: 42 },
					{ müdahaleAdı: "konservatif", müdahaleSayı: 241 },
					{ müdahaleAdı: "endodonti", müdahaleSayı: 68 },
					{ müdahaleAdı: "pedodonti", müdahaleSayı: 456 },
				],
			},
			{
				id: 8,
				müdahaleKategori: "ceromonti",
				müdahaleIstatistik: [
					{ müdahaleAdı: "diagnoz", müdahaleSayı: 98 },
					{ müdahaleAdı: "konservatif", müdahaleSayı: 45 },
					{ müdahaleAdı: "endodonti", müdahaleSayı: 356 },
					{ müdahaleAdı: "pedodonti", müdahaleSayı: 58 },
				],
			},
		],
	},
];

export const patients = [
	{
		id: 1,
		name: "Barış",
		lastName: "Korkmaz",
		gender: "Bay",
		clock: "11:00",
		descriptions: "Kanal tedavisine devam edilecek",
	},
	{
		id: 2,
		name: "Yusuf",
		lastName: "Kal",
		gender: "Bay",
		clock: "10:30",
		descriptions: "Diş Eti Absesi ve Periodontal Abseler",
	},
	{
		id: 3,
		name: "Ayşe",
		lastName: "Sağ",
		gender: "Bayan",
		clock: "09:30",
		descriptions: "Sağ arka 5 diş çekilecek",
	},
	{
		id: 4,
		name: "Fatma",
		lastName: "Yakut",
		gender: "Bayan",
		clock: "14:30",
		descriptions: "Diş taşı temizliği yapılacak",
	},
	{
		id: 5,
		name: "Ali",
		lastName: "Sağır",
		gender: "Bay",
		clock: "11:30",
		descriptions: "",
	},
	{
		id: 6,
		name: "Yusuf",
		lastName: "Solmaz",
		gender: "Bay",
		clock: "11:00",
		descriptions: "Damak yarılması",
	},
	{
		id: 7,
		name: "Tuğba",
		lastName: "Kılıç",
		gender: "Bayan",
		clock: "12:30",
		descriptions: "Diş teli yapımı",
	},
];
